-- 002: collapse the 162 orphan per-product substrates into two real ones.
--
-- WHY THIS IS BIGGER THAN IT LOOKS: of 170 substrate rows, 162 have ZERO systems
-- attached. Every hardware record (intel-nehalem, nvidia-ampere, zen-3, ...) got a
-- bespoke substrate row (intel-nehalem-die, nvidia-ampere-package, zen-3-chiplet)
-- that was never linked in system_substrates -- those systems are linked only to
-- the coarse 'electronic'. So collapsing the rows alone changes nothing visible;
-- this migration also LINKS the systems, which is what makes the substrate axis
-- mean something.
--
--   silicon-die           <- 145 orphan rows, 138 systems linked
--   discrete-logic-board  <- pre-VLSI machines, 7 systems linked
--
-- Systems keep their existing 'electronic' link; these are finer-grained, and the
-- substrate filter is OR-semantics, so both stay useful.
--
-- LEFT ALONE ON PURPOSE (not silicon CMOS logic -- collapsing them would assert
-- something false, e.g. that IonQ's vacuum chamber is a silicon die):
--   google-sycamore-chip, ibm-condor-chip, ibm-eagle-chip, ibm-osprey-chip,
--   ionq-chamber, lightmatter-passage-module, luminous-computing-module,
--   normal-computing-spu-module, ibm-analog-ai-module
-- These 9 are still orphans after this migration; they want their own pass.

.bail on
BEGIN;

INSERT OR REPLACE INTO substrates (id, name, description) VALUES
  ('silicon-die',
   'Silicon die',
   'Monolithic or chiplet CMOS silicon in a package: microprocessors, GPUs, NPUs, DSPs, microcontrollers, and wafer-scale parts. One substrate -- the process node, package and die area differ, the physics does not.'),
  ('discrete-logic-board',
   'Discrete logic board',
   'Pre-VLSI machines built from discrete transistors, SLT/TTL modules and card-and-backplane assemblies, where the computer is an assembly of boards rather than a die.');

INSERT OR IGNORE INTO system_substrates (system_id, substrate_id) VALUES
    ('alibaba-xuantie-c910', 'silicon-die'),
    ('amd-cdna', 'silicon-die'),
    ('amd-gcn', 'silicon-die'),
    ('amd-rdna', 'silicon-die'),
    ('amd-rdna2', 'silicon-die'),
    ('amd-rdna3', 'silicon-die'),
    ('amd-rdna4', 'silicon-die'),
    ('amd-terascale', 'silicon-die'),
    ('amd-zen', 'silicon-die'),
    ('amd-zen-2', 'silicon-die'),
    ('amd-zen-3', 'silicon-die'),
    ('amd-zen-4', 'silicon-die'),
    ('apple-ane', 'silicon-die'),
    ('apple-g3', 'silicon-die'),
    ('apple-g4', 'silicon-die'),
    ('apple-g5', 'silicon-die'),
    ('apple-gpu', 'silicon-die'),
    ('arm-cortex-a15', 'silicon-die'),
    ('arm-cortex-a53', 'silicon-die'),
    ('arm-cortex-a57', 'silicon-die'),
    ('arm-cortex-a72', 'silicon-die'),
    ('arm-cortex-a76', 'silicon-die'),
    ('arm-cortex-a78', 'silicon-die'),
    ('arm-cortex-a8', 'silicon-die'),
    ('arm-cortex-a9', 'silicon-die'),
    ('arm-cortex-m0', 'silicon-die'),
    ('arm-cortex-m0-plus', 'silicon-die'),
    ('arm-cortex-m3', 'silicon-die'),
    ('arm-cortex-m33', 'silicon-die'),
    ('arm-cortex-m4', 'silicon-die'),
    ('arm-cortex-m55', 'silicon-die'),
    ('arm-cortex-m7', 'silicon-die'),
    ('arm-cortex-m85', 'silicon-die'),
    ('arm-cortex-x1', 'silicon-die'),
    ('arm-cortex-x2', 'silicon-die'),
    ('arm-cortex-x4', 'silicon-die'),
    ('arm-mali-g12x', 'silicon-die'),
    ('arm-mali-g5x', 'silicon-die'),
    ('arm-mali-g7x', 'silicon-die'),
    ('arm-mali-g9x', 'silicon-die'),
    ('arm-mali-t6xx', 'silicon-die'),
    ('arm-neoverse-n1', 'silicon-die'),
    ('arm-neoverse-v1', 'silicon-die'),
    ('arm2', 'silicon-die'),
    ('arm6', 'silicon-die'),
    ('arm7tdmi', 'silicon-die'),
    ('arm9', 'silicon-die'),
    ('avr-atmega', 'silicon-die'),
    ('avr-attiny', 'silicon-die'),
    ('avr32', 'silicon-die'),
    ('aws-inferentia', 'silicon-die'),
    ('aws-trainium', 'silicon-die'),
    ('cell-be', 'silicon-die'),
    ('cerebras-wse', 'silicon-die'),
    ('ceva-dsp-cores', 'silicon-die'),
    ('dec-alpha-21064', 'silicon-die'),
    ('esp32-c3', 'silicon-die'),
    ('esp32-c6', 'silicon-die'),
    ('gd32vf', 'silicon-die'),
    ('google-tpu-v1', 'silicon-die'),
    ('google-tpu-v2', 'silicon-die'),
    ('google-tpu-v3', 'silicon-die'),
    ('google-tpu-v4', 'silicon-die'),
    ('google-tpu-v5', 'silicon-die'),
    ('graphcore-ipu', 'silicon-die'),
    ('groq-tsp', 'silicon-die'),
    ('hp-pa-risc', 'silicon-die'),
    ('imagination-powervr', 'silicon-die'),
    ('intel-286', 'silicon-die'),
    ('intel-386', 'silicon-die'),
    ('intel-486', 'silicon-die'),
    ('intel-8051', 'silicon-die'),
    ('intel-8086', 'silicon-die'),
    ('intel-alder-lake-hybrid', 'silicon-die'),
    ('intel-core-yonah', 'silicon-die'),
    ('intel-haswell', 'silicon-die'),
    ('intel-itanium', 'silicon-die'),
    ('intel-loihi-1', 'silicon-die'),
    ('intel-nehalem', 'silicon-die'),
    ('intel-p6-pentium-pro', 'silicon-die'),
    ('intel-pentium', 'silicon-die'),
    ('intel-pentium-4-netburst', 'silicon-die'),
    ('intel-sandy-bridge', 'silicon-die'),
    ('intel-skylake', 'silicon-die'),
    ('intel-xe-hpc', 'silicon-die'),
    ('intel-xe-hpg', 'silicon-die'),
    ('intel-xe-lp', 'silicon-die'),
    ('intel-xe2', 'silicon-die'),
    ('microchip-pic10', 'silicon-die'),
    ('microchip-pic12', 'silicon-die'),
    ('microchip-pic16', 'silicon-die'),
    ('microchip-pic18', 'silicon-die'),
    ('microchip-pic24', 'silicon-die'),
    ('microchip-pic32', 'silicon-die'),
    ('mill-computing', 'silicon-die'),
    ('mips-r2000', 'silicon-die'),
    ('mips-r3000', 'silicon-die'),
    ('nvidia-ampere', 'silicon-die'),
    ('nvidia-blackwell', 'silicon-die'),
    ('nvidia-fermi', 'silicon-die'),
    ('nvidia-hopper', 'silicon-die'),
    ('nvidia-kepler', 'silicon-die'),
    ('nvidia-maxwell', 'silicon-die'),
    ('nvidia-pascal', 'silicon-die'),
    ('nvidia-tesla', 'silicon-die'),
    ('nvidia-turing', 'silicon-die'),
    ('nvidia-volta', 'silicon-die'),
    ('power1', 'silicon-die'),
    ('power10', 'silicon-die'),
    ('power2', 'silicon-die'),
    ('power3', 'silicon-die'),
    ('power4', 'silicon-die'),
    ('power5', 'silicon-die'),
    ('power6', 'silicon-die'),
    ('power7', 'silicon-die'),
    ('power8', 'silicon-die'),
    ('power9', 'silicon-die'),
    ('qualcomm-hexagon', 'silicon-die'),
    ('qualcomm-hexagon-npu', 'silicon-die'),
    ('sambanova-rdu', 'silicon-die'),
    ('samsung-hbm-pim', 'silicon-die'),
    ('sifive-u54', 'silicon-die'),
    ('sifive-u74', 'silicon-die'),
    ('sifive-x280', 'silicon-die'),
    ('sparc', 'silicon-die'),
    ('spinnaker', 'silicon-die'),
    ('sun-sparc-v8', 'silicon-die'),
    ('sun-sparc-v9', 'silicon-die'),
    ('tensilica-xtensa', 'silicon-die'),
    ('tenstorrent-grayskull', 'silicon-die'),
    ('tenstorrent-wormhole', 'silicon-die'),
    ('ti-msp430', 'silicon-die'),
    ('ti-tms320-c2000', 'silicon-die'),
    ('ti-tms320-c5000', 'silicon-die'),
    ('ti-tms320-c6000', 'silicon-die'),
    ('transmeta-crusoe', 'silicon-die'),
    ('upmem-pim', 'silicon-die'),
    ('ventana-veyron', 'silicon-die');

INSERT OR IGNORE INTO system_substrates (system_id, substrate_id) VALUES
    ('cdc-6600', 'discrete-logic-board'),
    ('dec-pdp-11', 'discrete-logic-board'),
    ('dec-pdp-8', 'discrete-logic-board'),
    ('dec-vax', 'discrete-logic-board'),
    ('ibm-system-360', 'discrete-logic-board'),
    ('manchester-dataflow', 'discrete-logic-board'),
    ('mit-tagged-token', 'discrete-logic-board');

-- Drop the collapsed rows. Safe: they hold no system_substrates links (verified),
-- so nothing is orphaned by removing them.
DELETE FROM substrates WHERE id IN (

    'advanced-microprocessor-die',
    'alder-lake-die-package',
    'alibaba-c910-die',
    'amd-cdna-package',
    'amd-gcn-package',
    'amd-rdna-package',
    'amd-rdna2-package',
    'amd-rdna3-package',
    'amd-rdna4-package',
    'amd-terascale-package',
    'apple-ane-die',
    'apple-g3-package',
    'apple-g4-package',
    'apple-g5-module',
    'apple-silicon-gpu-package',
    'arm-cortex-a15-die',
    'arm-cortex-a53-die',
    'arm-cortex-a57-die',
    'arm-cortex-a72-die',
    'arm-cortex-a76-die',
    'arm-cortex-a78-die',
    'arm-cortex-a8-die',
    'arm-cortex-a9-die',
    'arm-cortex-x1-die',
    'arm-cortex-x2-die',
    'arm-cortex-x4-die',
    'arm-mali-g12x-package',
    'arm-mali-g5x-package',
    'arm-mali-g7x-package',
    'arm-mali-g9x-package',
    'arm-mali-t6xx-package',
    'arm2-die-board',
    'arm6-package',
    'arm7tdmi-package',
    'arm9-package',
    'avr-atmega-package',
    'avr-attiny-package',
    'avr32-package',
    'aws-inferentia-package',
    'aws-trainium-package',
    'cdc-6600-core',
    'cell-be-die',
    'cerebras-wse-wafer',
    'ceva-dsp-die',
    'cortex-m0-package',
    'cortex-m0p-package',
    'cortex-m3-package',
    'cortex-m33-package',
    'cortex-m4-package',
    'cortex-m55-package',
    'cortex-m7-package',
    'cortex-m85-package',
    'crusoe-die',
    'dec-alpha-21064-ceramic-mod',
    'dec-alpha-21064-module',
    'dec-pdp-11-backplane',
    'dec-pdp-8-chassis',
    'dec-vax-modules',
    'esp32-c3-package',
    'esp32-c6-package',
    'gd32vf-package',
    'google-tpu-v1-die',
    'google-tpu-v2-die',
    'google-tpu-v3-die',
    'google-tpu-v4-die',
    'google-tpu-v5-die',
    'graphcore-ipu-module',
    'groq-tsp-die',
    'haswell-die-package',
    'hp-pa-risc-die',
    'intel-286-cmos-die',
    'intel-486-package-die',
    'intel-8051-package',
    'intel-nehalem-die',
    'intel-netburst-core',
    'intel-p5',
    'intel-p6-silicon',
    'intel-sandy-bridge-die',
    'intel-xe-hpc-package',
    'intel-xe-hpg-package',
    'intel-xe-lp-package',
    'intel-xe2-package',
    'intel-yonah-die',
    'itanium-module',
    'loihi-1-module',
    'manchester-dataflow-hardware',
    'mill-computing-die',
    'mips-r2000-die',
    'mips-r3000-package',
    'mips-r3000-silicon-package',
    'mit-tagged-token-hardware',
    'msp430-package',
    'multi-board-backplane-assembly',
    'neoverse-n1-die',
    'neoverse-v1-die',
    'nmos-cmos-die-ceramic-dip',
    'nvidia-ampere-package',
    'nvidia-blackwell-package',
    'nvidia-fermi-package',
    'nvidia-hopper-package',
    'nvidia-kepler-package',
    'nvidia-maxwell-package',
    'nvidia-pascal-package',
    'nvidia-tesla-package',
    'nvidia-turing-package',
    'nvidia-volta-package',
    'pic10-package',
    'pic12-package',
    'pic16-package',
    'pic18-package',
    'pic24-package',
    'pic32-package',
    'power1-die-module',
    'power10-die',
    'power2-module',
    'power3-module',
    'power4-module',
    'power5-module',
    'power6-module',
    'power7-chip-module',
    'power8-package',
    'power9-die',
    'powervr-package',
    'qualcomm-hexagon-die',
    'qualcomm-hexagon-npu-package',
    'sambanova-rdu-tile',
    'samsung-hbm-pim-stack',
    'sifive-u54-die',
    'sifive-u74-die',
    'sifive-x280-die',
    'silicon-die-memory-subsystem',
    'silicon_cmos_packaged_core',
    'skylake-die-package',
    'sparc-die',
    'spinnaker-chipboard',
    'sun-sparc-v8-die',
    'sun-sparc-v9-die',
    'tensilica-xtensa-die',
    'tenstorrent-grayskull-package',
    'tenstorrent-wormhole-package',
    'ti-tms320-c2000-package',
    'ti-tms320-c5000-package',
    'ti-tms320-c6000-package',
    'transistor-board-frame',
    'transistorized-ttl-cmos-rack-mounted',
    'transistorized_cmos_logic',
    'ultrasparc-v9-die',
    'upmem-pim-module',
    'ventana-veyron-die',
    'zen-2-chiplet',
    'zen-3-chiplet',
    'zen-4-chiplet',
    'zen-die-module'
);

-- Post-checks
SELECT 'substrate rows' AS check_, COUNT(*) AS n FROM substrates;
SELECT 'orphan substrates' AS check_, COUNT(*) AS n FROM substrates
  WHERE id NOT IN (SELECT substrate_id FROM system_substrates);
SELECT 'dangling links' AS check_, COUNT(*) AS n FROM system_substrates ss
  WHERE NOT EXISTS (SELECT 1 FROM substrates s WHERE s.id = ss.substrate_id)
     OR NOT EXISTS (SELECT 1 FROM systems y WHERE y.id = ss.system_id);
SELECT s.name, COUNT(ss.system_id) AS systems FROM substrates s
  LEFT JOIN system_substrates ss ON s.id = ss.substrate_id
  GROUP BY s.id ORDER BY systems DESC;

COMMIT;
